// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBd1qaxzL-Zk3B8AsblsaNQTMqUqQlDzg',
    appId: '1:117443847583:web:5f5e9e8f5b498f67f049aa',
    messagingSenderId: '117443847583',
    projectId: 'service-spot-28646',
    authDomain: 'service-spot-28646.firebaseapp.com',
    storageBucket: 'service-spot-28646.firebasestorage.app',
    measurementId: 'G-DFWH82307M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFRWZ5dryj4VvUdFfShD07PoImUXcek9k',
    appId: '1:117443847583:android:e37c6128973e465af049aa',
    messagingSenderId: '117443847583',
    projectId: 'service-spot-28646',
    storageBucket: 'service-spot-28646.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARd0HeOOIU798tCGNS4OpzuAPDg_MEKf0',
    appId: '1:117443847583:ios:1c6b86998c954960f049aa',
    messagingSenderId: '117443847583',
    projectId: 'service-spot-28646',
    storageBucket: 'service-spot-28646.firebasestorage.app',
    iosBundleId: 'com.example.servicespot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARd0HeOOIU798tCGNS4OpzuAPDg_MEKf0',
    appId: '1:117443847583:ios:1c6b86998c954960f049aa',
    messagingSenderId: '117443847583',
    projectId: 'service-spot-28646',
    storageBucket: 'service-spot-28646.firebasestorage.app',
    iosBundleId: 'com.example.servicespot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBd1qaxzL-Zk3B8AsblsaNQTMqUqQlDzg',
    appId: '1:117443847583:web:64d605a8cb4f5417f049aa',
    messagingSenderId: '117443847583',
    projectId: 'service-spot-28646',
    authDomain: 'service-spot-28646.firebaseapp.com',
    storageBucket: 'service-spot-28646.firebasestorage.app',
    measurementId: 'G-9C7KQGLXBB',
  );
}
